### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by daisyyoo** [daisyyoo/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add location to car's x and y coordinates on page based on data model
- [x] Make image absolute position
- [x] Read about style property of element objects and use to change top and left offset styles for the car
- [x] Move car every 16 ms for smooth movement
- [x] The car will start moving when user presses space
- [x] The car will repeat moving a few pixels right every 16ms without stopping 
- [x] Only focus on the car moving right for now
