### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by daisyyoo** [daisyyoo/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [ ] Stop the car if the user presses space again 
- [ ] Must resume where it left off 
- [ ] If not stopped, the car shall keep going until it's off the page
